---
- name: Advanced System Monitoring Playbook
  hosts: all  # Replace with your target hosts or groups
  gather_facts: true

  tasks:
    - name: Get system information
      ansible.builtin.debug:
        var: ansible_facts

    - name: Check system uptime
      ansible.builtin.command: uptime
      register: uptime_output
      changed_when: false

    - name: Print system uptime
      ansible.builtin.debug:
        msg: "System uptime: {{ uptime_output.stdout }}"

    - name: Check MySQL service status
      ansible.builtin.systemd:
        name: mysql
        state: status
      register: mysql_status
      ignore_errors: yes

    - name: Print MySQL service status
      ansible.builtin.debug:
        msg: "MySQL service is {{ 'running' if mysql_status.status == 'active' else 'not running' }}"

    - name: Check Nginx service status
      ansible.builtin.systemd:
        name: nginx
        state: status
      register: nginx_status
      ignore_errors: yes

    - name: Print Nginx service status
      ansible.builtin.debug:
        msg: "Nginx service is {{ 'running' if nginx_status.status == 'active' else 'not running' }}"

    - name: Check ClamAV service status
      ansible.builtin.systemd:
        name: clamav-daemon
        state: status
      register: clamav_status
      ignore_errors: yes

    - name: Print ClamAV service status
      ansible.builtin.debug:
        msg: "ClamAV service is {{ 'running' if clamav_status.status == 'active' else 'not running' }}"

    - name: Get package versions
      ansible.builtin.command: dpkg-query --showformat='${Package} ${Version}\n' --show
      register: package_versions
      changed_when: false

    - name: Print package versions
      ansible.builtin.debug:
        var: package_versions.stdout_lines

    - name: Check port availability
      ansible.builtin.wait_for:
        host: localhost  # Replace with the host you want to check
        port: 80         # Replace with the port number you want to check
        timeout: 5
      register: port_available
      failed_when: false

    - name: Print port availability
      ansible.builtin.debug:
        msg: "Port 80 is {{ 'open' if port_available.is_reachable else 'closed' }}"

    # Add more tasks for additional monitoring checks
    # ...

  # Add more roles or tasks as needed for your monitoring requirements
  # ...
