---
- name: Advanced System Monitoring Playbook
  hosts: all  # Replace with your target hosts or groups
  gather_facts: true

  tasks:
    - name: Get system information
      ansible.builtin.debug:
        var: ansible_facts

    - name: Check system uptime
      ansible.builtin.command: uptime
      register: uptime_output
      changed_when: false

    - name: Print system uptime
      ansible.builtin.debug:
        msg: "System uptime: {{ uptime_output.stdout }}"

    - name: Check ClamAV service status
      ansible.builtin.systemd:
        name: clamav-daemon
        enabled: yes
      register: clamav_status
      changed_when: false

    - name: Print ClamAV service status
      ansible.builtin.debug:
        msg: "ClamAV service is {{ 'enabled' if clamav_status.changed else 'not enabled' }}"

    - name: Get package versions
      ansible.builtin.command: dpkg-query --showformat='${Package} ${Version}\n' --show
      register: package_versions
      changed_when: false

    - name: Print package versions
      ansible.builtin.debug:
        msg: "{{ package_versions.stdout_lines | join('\n') }}"

    - name: Check port availability
      ansible.builtin.wait_for:
        host: localhost  # Replace with the host you want to check
        port: 80         # Replace with the port number you want to check
        timeout: 5
      register: port_available
      failed_when: false

    - name: Print port availability
      ansible.builtin.debug:
        msg: "Port 80 is {{ 'open' if port_available.is_reachable else 'closed' }}"

    - name: Check available RAM
      ansible.builtin.command: free -h
      register: ram_status
      changed_when: false

    - name: Print available RAM
      ansible.builtin.debug:
        msg: |
          Available RAM:
          {{ ram_status.stdout | indent(4) }}

    - name: Check disk space
      ansible.builtin.shell: df -h
      register: disk_space
      changed_when: false

    - name: Print disk space
      ansible.builtin.debug:
        msg: |
          Disk space:
          {{ disk_space.stdout | indent(4) }}

    # Add more tasks for additional monitoring checks
    # ...

  # Add more roles or tasks as needed for your monitoring requirements
  # ...
